#!/bin/sh
mkdir unangband-062-src
mkdir unangband-062-src/lib
mkdir unangband-062-src/lib/apex
mkdir unangband-062-src/lib/bone
mkdir unangband-062-src/lib/data
mkdir unangband-062-src/lib/edit
mkdir unangband-062-src/lib/file
mkdir unangband-062-src/lib/help
mkdir unangband-062-src/lib/info
mkdir unangband-062-src/lib/pref
mkdir unangband-062-src/lib/save
mkdir unangband-062-src/lib/todo
mkdir unangband-062-src/lib/user
mkdir unangband-062-src/lib/xtra
mkdir unangband-062-src/lib/xtra/font
mkdir unangband-062-src/lib/xtra/graf
mkdir unangband-062-src/lib/xtra/music
mkdir unangband-062-src/lib/xtra/sound
mkdir unangband-062-src/lib/xtra/help
mkdir unangband-062-src/src
mkdir unangband-062-src/src/osx
mkdir unangband-062-src/src/osx/English.lproj
mkdir unangband-062-src/src/osx/English.lproj/main.nib

cp lib/apex/delete.me unangband-062-src/lib/apex
cp lib/bone/delete.me unangband-062-src/lib/bone
cp lib/data/delete.me unangband-062-src/lib/data
cp lib/save/delete.me unangband-062-src/lib/save
cp lib/user/delete.me unangband-062-src/lib/user
cp lib/xtra/font/delete.me unangband-062-src/lib/xtra/font
cp lib/xtra/graf/delete.me unangband-062-src/lib/xtra/graf
cp lib/xtra/music/delete.me unangband-062-src/lib/xtra/music

cp *.txt unangband-062-src
cp *.bat unangband-062-src
cp config* unangband-062-src
cp install* unangband-062-src

cp Makefile* unangband-062-src
cp *.m4 unangband-062-src

cp lib/Makefile* unangband-062-src/lib
cp lib/apex/Makefile* unangband-062-src/lib/apex
cp lib/bone/Makefile* unangband-062-src/lib/bone
cp lib/data/Makefile* unangband-062-src/lib/data
cp lib/edit/Makefile* unangband-062-src/lib/edit
cp lib/file/Makefile* unangband-062-src/lib/file
cp lib/help/Makefile* unangband-062-src/lib/help
cp lib/info/Makefile* unangband-062-src/lib/info
cp lib/pref/Makefile* unangband-062-src/lib/pref
cp lib/save/Makefile* unangband-062-src/lib/save
cp lib/todo/Makefile* unangband-062-src/lib/todo
cp lib/user/Makefile* unangband-062-src/lib/user
cp lib/xtra/Makefile* unangband-062-src/lib/xtra
cp lib/xtra/font/Makefile* unangband-062-src/lib/xtra/font
cp lib/xtra/graf/Makefile* unangband-062-src/lib/xtra/graf
cp lib/xtra/music/Makefile* unangband-062-src/lib/xtra/music
cp lib/xtra/sound/Makefile* unangband-062-src/lib/xtra/sound
cp lib/xtra/help/Makefile* unangband-062-src/lib/xtra/help
cp src/Makefile* unangband-062-src/src

cp lib/edit/*.txt unangband-062-src/lib/edit
cp lib/file/*.txt unangband-062-src/lib/file
cp lib/info/*.txt unangband-062-src/lib/info
cp lib/help/*.txt unangband-062-src/lib/help
cp lib/help/*.hlp unangband-062-src/lib/help
cp lib/pref/*.prf unangband-062-src/lib/pref
cp lib/todo/*.txt unangband-062-src/lib/todo

cp lib/xtra/font/*.fon unangband-062-src/lib/xtra/font
cp lib/xtra/graf/*.bmp unangband-062-src/lib/xtra/graf
cp lib/xtra/sound/*.wav unangband-062-src/lib/xtra/sound

cp lib/xtra/sound/sound.cfg unangband-062-src/lib/xtra/sound
cp lib/xtra/help/angband.hlp unangband-062-src/lib/xtra/help
cp lib/xtra/help/angband.cnt unangband-062-src/lib/xtra/help

cp src/*.h unangband-062-src/src
cp src/*.c unangband-062-src/src
cp src/*.inc unangband-062-src/src
cp src/*.rc unangband-062-src/src
cp src/*.ico unangband-062-src/src
cp src/Makefile* unangband-062-src/src

cp src/osx/*.icns unangband-062-src/src/osx
cp src/osx/*.xml unangband-062-src/src/osx
cp src/osx/*.h unangband-062-src/src/osx
cp src/osx/English.lproj/*.strings unangband-062-src/src/osx/English.lproj
cp src/osx/English.lproj/main.nib/*.nib unangband-062-src/src/osx/English.lproj/main.nib

zip -9 -r unangband-062-src.zip unangband-062-src

